### ISSUE TITLE
About Long-horizon BC

### ISSUE THREAD

**Issue by MK-D-Luffy** [pairlab/QueST#16]
Hello, is your long-range task to train the autoencoder and prior on libero_long, and then perform evaluation? Is the final accuracy shown in the figure below?
![image](https://github.com/user-attachments/assets/79fa35c6-db01-4c2c-8e97-607a02989ba4)

**Comment by atharvamete** [comment]
> is your long-range task to train the autoencoder and prior on libero_long

yes
This plot is as per our previous codebase where we directly implemented inside the libero repo. In the current codebase I'm seeing numbers as 75, 54, 34, 38, 60 for ResNet-T, ACT, Diffusion Policy, VQ-BeT and QueST.
I'm not sure if this is due to some difference in the way we implemented libero evaluation. This certainly needs more investigation from our side. Feel free to report your numbers here as well.

**Comment by MK-D-Luffy** [comment]
Hello, what about the few-shot tasks? Are they the same as in the paper, or have there been any changes?
![image](https://github.com/user-attachments/assets/dd266506-c6b0-4131-b47d-d2aea9d54973)

**Comment by atharvamete** [comment]
Hi, we haven't tried these on this codebase so can't say. All the metaworld results are as per this codebase. I'll get back with an update.
