### ISSUE TITLE
Performance reproduction issue for diffusion models

### ISSUE THREAD

**Issue by AtharvanDogra** [pairlab/QueST#19]
Hi @atharvamete, thanks for the awesome work and well-structured code.

I'm unable to match the performance for diffusion policy shown in your Figure 2 (a), i.e., 75%. I use the `train_base.yaml` file and `diffusion_policy` as algorithm to train the policy with `libero_90` task following the default configuration as given in your code. 
I use `skill_block_size: 32` and `action_horizon: 16` while inferencing, as stated in Appendix B.3 (changing from 16 and 2 which was in the default `diffusion_policy` config). 

Also, as I'm new to this, can you confirm if the `skill_block_size` and `action_horizon` don't matter during the training of a diffusion model? 

<img width="517" alt="Screenshot 2024-11-28 at 8 22 50 PM" src="https://github.com/user-attachments/assets/a18e1644-81c5-41ca-95bb-0d98710202d1">

Attaching a pic of the inference time and the final eval performance. 
Can you also confirm if this is the normal evaluation time for inference with diffusion model? The quest evaluation took around 7 hrs.

**Comment by atharvamete** [comment]
Thanks.

This is an ongoing issue and is impacting all baselines (and even quest). The published results are from before we went a major refactor. I think the issue is mostly either with libero env implementation. I'll work on resolving this but not anytime soon. Apologies for that.

> can you confirm if the skill_block_size and action_horizon don't matter during the training of a diffusion model?

The skill_block_size is the input action sequence length which matter during training for all models that take action chunk including diffusion policy. action_horizon matters during inference not training.
We should have named skill_block_size as action_chunk and action_horizon as execution_horizon. I might do this.
If you run parallel evals then it should take less time than that

**Comment by AtharvanDogra** [comment]
@atharvamete Got it. Thanks for the detailed response.
